---
title: "NASA Datanuats"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(leaflet)
library(dplyr)
library(tidyr)
library(stringr)
library(forcats)
library(DT)
#library(wordcloud)
library(crosstalk)
library(wordcloud2)
```

Column {}
-----------------------------------------------------------------------
### 

```{r}
load("datanauts.Rdata")

#leaflet() %>%
#    addTiles() %>%
#   setView(-2.237430, 53.48095, zoom = 2) %>%
#    addCircleMarkers(data = datanauts, lng =~ lon, lat = ~ lat, group = "All Members", color = "blue") %>% 
#    addCircleMarkers(data = filter(datanauts, class == "Founding Class (2015)"), lng = ~ lon, lat = ~ lat, group = "Founding Class", color = "green") %>% 
#    addCircleMarkers(data = filter(datanauts, class == "2016"), lng = ~ lon, lat = ~ lat, group = "2016", color = "purple") %>% 
#    addCircleMarkers(data = filter(datanauts, class == "Spring 2017"), lng = ~ lon, lat = ~ lat, group = "Spring 2017", color = "red") %>% 
#    addCircleMarkers(data = filter(datanauts, class == "Fall 2017"), lng = ~ lon, lat = ~ lat, group = "Fall 2017", color = "cyan") %>% 
#    hideGroup("Founding Class") %>% 
#    hideGroup("2016") %>% 
#    hideGroup("Spring 2017") %>% 
#    hideGroup("Fall 2017") %>%
#    addLayersControl(baseGroups = "Members", overlayGroups = c("All Members", "Founding Class", "2016", "Spring 2017", "Fall 2017"),
#                     options = layersControlOptions(collapsed = FALSE))


shared_datanauts <- SharedData$new(select(datanauts, name, location, industry, class, lon, lat))
filter_select("NDClass", "Datanaut Class Map", shared_datanauts, group = ~class, allLevels = TRUE)

leaflet() %>%
    setView(-82.831040,35.88904, zoom = 2) %>% 
    addTiles() %>%
    addCircleMarkers(data = shared_datanauts, lng =~ lon, lat = ~ lat, group = "Members", color = "blue") %>% 
    addCircleMarkers(data = filter(datanauts, class == "Founding Class (2015)"), lng = ~ lon, lat = ~ lat, group = "Founding Class", color = "green") %>% 
    addCircleMarkers(data = filter(datanauts, class == "2016"), lng = ~ lon, lat = ~ lat, group = "2016", color = "purple") %>% 
    addCircleMarkers(data = filter(datanauts, class == "Spring 2017"), lng = ~ lon, lat = ~ lat, group = "Spring 2017", color = "red") %>% 
    addCircleMarkers(data = filter(datanauts, class == "Fall 2017"), lng = ~ lon, lat = ~ lat, group = "Fall 2017", color = "cyan") %>% 
    hideGroup("Founding Class") %>% 
    hideGroup("2016") %>% 
    hideGroup("Spring 2017") %>% 
    hideGroup("Fall 2017") %>%
    addLayersControl(baseGroups = "Members", overlayGroups = c("Members", "Founding Class", "2016", "Spring 2017", "Fall 2017"),
                     options = layersControlOptions(collapsed = FALSE))



```

Column {}
-----------------------------------------------------------------------
###

```{r}
# datatable(datanauts %>% select(name, location, industry, class))
#filter_select("NDClass", "Datanaut Class", shared_datanauts, group = ~class, allLevels = TRUE)
datatable(shared_datanauts)
```

###

```{r}
datanaut_sub <- datanauts %>% select(name, location, industry, class)
datanaut_sub <- datanaut_sub %>% separate_rows(industry, sep = ",")
datanaut_sub$industry <- str_trim(datanaut_sub$industry)
datanaut_sub$industry <- factor(datanaut_sub$industry)

industry_count <- fct_count(datanaut_sub$industry, sort = TRUE)

wordcloud2(industry_count, size = .5, color = "random-light", backgroundColor = "grey")

```

